TOOL_DESCRIPTION = {
    "str_replace": (
        "Performs exact string replacement in an existing file (atomic write).\n"
        "Parameters:\n"
        "- file_path: file path relative to workspace root\n"
        "- old_str: the exact text to replace (must match exactly, including whitespace/indentation)\n"
        "- new_str: the replacement text\n"
        "- replace_all: if True, replaces ALL occurrences of old_str (default False)\n"
        "\n"
        "CRITICAL — Making old_str unique:\n"
        "The old_str must match EXACTLY one location in the file (unless replace_all=True).\n"
        "To guarantee uniqueness, ALWAYS include 2-3 lines of surrounding context:\n"
        "  GOOD: old_str='    def login(self):\\n        return self._auth.login()'\n"
        "  BAD:  old_str='return self._auth.login()'  ← probably appears many times\n"
        "Include the EXACT indentation (tabs/spaces) as shown by view_file.\n"
        "\n"
        "ERROR RECOVERY — When str_replace fails, do NOT retry blindly:\n"
        "- 'Text not found in X': The old_str you provided does not match.\n"
        "  → Call view_file on the file, copy the EXACT text you want to replace\n"
        "    (including all whitespace and indentation).\n"
        "- 'Text matches N occurrences in X': Your old_str is not unique enough.\n"
        "  → Include MORE surrounding context lines (2-3 additional lines above AND below)\n"
        "    to make the match unique, OR use replace_all=True if you want to replace all.\n"
        "\n"
        "BEST PRACTICES:\n"
        "- Use this tool for surgical edits to existing files. NEVER use write_file for edits.\n"
        "- Do NOT use for creating new files — use write_file instead.\n"
        "- Break large changes into multiple smaller str_replace calls. Each call should\n"
        "  change a focused, contiguous block of code (5-20 lines ideal).\n"
        "- The operation is atomic — the file will never be corrupted, even if the write fails.\n"
        "\n"
        "Returns a JSON object with status, message, path, and diff fields.\n"
        "\n"
        "Examples:\n"
        "  file_path='config.py', old_str='DEBUG = True', new_str='DEBUG = False'\n"
        "  file_path='app.py', old_str='old_var', new_str='new_var', replace_all=True\n"
        "  file_path='agent/graph.py',\n"
        "    old_str='def build():\\n    return StateGraph(AgentState)\\n    graph.add_node(\"think\", think)',\n"
        "    new_str='def build():\\n    return StateGraph(AgentState)\\n    graph.add_node(\"custom\", custom_node)'"
    ),
    "write_file": (
        "Create a new file or overwrite an existing one with full content (atomic write).\n"
        "Parameters:\n"
        "- file_path: file path relative to workspace root\n"
        "- content: the complete file content as a string\n"
        "Parent directories are created automatically if they don't exist.\n"
        "Returns a JSON object with status, message ([CREATED] or [OVERWRITTEN]), "
        "path, and diff (old/new content).\n"
        "\n"
        "TOOL SELECTION — When to use write_file vs str_replace:\n"
        "  USE write_file WHEN:\n"
        "    - Creating a brand new file that doesn't exist yet\n"
        "    - You need to COMPLETELY rewrite a file from scratch\n"
        "  DO NOT use write_file WHEN:\n"
        "    - Making a small edit to a few lines → use str_replace instead\n"
        "    - Changing one function/class in a large file → use str_replace\n"
        "\n"
        "WARNING: write_file overwrites the ENTIRE file. If you only need to change\n"
        "a few lines, you will waste tokens and risk losing existing code.\n"
        "When in doubt, use str_replace.\n"
        "\n"
        "Example:\n"
        "  file_path='utils/helper.py', content='def add(a, b):\\n    return a + b\\n'"
    ),
}
