TOOL_DESCRIPTION = {
    "glob": (
        "Search for files matching a glob pattern. Supports ** for recursive matching.\n"
        "Parameters:\n"
        "- pattern: glob pattern to match file paths against (e.g. '*.py', '**/*.ts')\n"
        "- dir_path: directory to search in, relative to workspace root (default '.')\n"
        "- allow_external_reads: if True, allows searching outside workspace root (default False)\n"
        "Returns a JSON object with matching file paths (absolute paths), "
        "count, pattern, and a truncated flag. Capped at 100 results.\n"
        "Use this tool when:\n"
        "- You need to find files by name pattern (e.g. '**/*.py' for all Python files)\n"
        "- You're exploring project structure and don't know exact file paths\n"
        "Do NOT use this tool when you already know the exact file path.\n"
        "\n"
        "TROUBLESHOOTING:\n"
        "- If count=0: the pattern didn't match. Try a broader pattern (e.g. '*' instead of '*.py'), "
        "or a different dir_path.\n"
        "- If truncated=true: more than 100 files matched. Narrow the search with a specific "
        "dir_path or a more precise pattern.\n"
        "- Use '**/*.ext' (with **) to search ALL subdirectories recursively. "
        "Without **, the pattern only matches files in the immediate directory.\n"
        "\n"
        "Examples:\n"
        "  pattern='**/*.py' → all .py files in workspace\n"
        "  pattern='**/*.tsx', dir_path='src' → all .tsx files under src/"
    ),
    "view_file": (
        "Read a specific range of lines from a file, with structured line numbers.\n"
        "Parameters:\n"
        "- file_path: file path relative to workspace root\n"
        "- offset: starting line number (1-based, default 1)\n"
        "- limit: maximum lines to read (default 100)\n"
        "- allow_external_reads: if True, allows reading files outside workspace root (default False)\n"
        "Returns a JSON object with status, path, total_lines, start_line, "
        "end_line, remaining, and an array of line objects.\n"
        "Each line object format: {\"line_no\": integer_line_number, \"content\": string_code_line}.\n"
        "Use this tool BEFORE editing any file — never edit a file you haven't read.\n"
        "Fails with JSON error if: file doesn't exist, path is a directory, "
        "offset exceeds total lines, file is binary, permission denied, or file exceeds size limit.\n"
        "\n"
        "PAGINATION — the 'remaining' field tells you how many more lines exist:\n"
        "- If remaining > 0: you have NOT seen the whole file! Call view_file again\n"
        "  with offset = end_line + 1 to read the next block.\n"
        "- If remaining == 0: you've reached the end of the file. No more lines.\n"
        "\n"
        "TROUBLESHOOTING:\n"
        "- If status=error with 'exceeds total lines': your offset is past the end.\n"
        "  Use a smaller offset, or check total_lines from a previous call.\n"
        "- If you see 'remaining: 34' in the output, that means 34 more lines exist.\n"
        "  Re-read with offset=N to see them before making edits near the end of the file.\n"
        "- Binary file error means this file cannot be parsed as plain text.\n"
        "\n"
        "Example returned lines field:\n"
        "\"lines\": [\n"
        "  {\"line_no\": 1, \"content\": \"public class Test {\"},\n"
        "  {\"line_no\": 2, \"content\": \"    public static void main(String[] args) {\"}\n"
        "]\n"
        "\n"
        "Usage Example:\n"
        "  file_path='agent/graph.py', offset=1, limit=30 → first 30 lines of graph.py\n"
        "  file_path='agent/graph.py', offset=31, limit=30 → next 30 lines (if file > 30 lines)"
    ),
    "grep": (
        "Search file contents using regular expressions.\n"
        "Parameters:\n"
        "- pattern: regex pattern to search for (Python re syntax)\n"
        "- path: file or directory to search in (default '.')\n"
        "- glob_pattern: glob to filter file names (e.g. '*.py', default searches all files)\n"
        "- output_mode: 'files_with_matches' (default) | 'content' | 'count'\n"
        "- context_lines: +/-N lines context around each match in content mode (default 2)\n"
        "- head_limit: max results to return (default 200, 0=unlimited)\n"
        "- offset: skip first N results for pagination (default 0)\n"
        "- case_sensitive: whether to match case (default True)\n"
        "- multiline: if True, '.' matches newlines, patterns can span lines (default False)\n"
        "- allow_external_reads: if True, allows searching outside workspace root (default False)\n"
        "\n"
        "grep is a NAVIGATION tool, not a reading tool. Use it to FIND where code lives,\n"
        "not to UNDERSTAND it. The default output_mode is 'files_with_matches' — you get\n"
        "only file paths. After grep tells you WHERE the code is, you MUST use view_file\n"
        "to read the actual file content before making any edits.\n"
        "\n"
        "OUTPUT MODE STRATEGY — which mode to use when:\n"
        "  1. Start with 'files_with_matches' (default) to locate relevant files\n"
        "  2. Use 'count' to quickly see distribution across files\n"
        "  3. Use 'content' on a SPECIFIC file/folder to see matched lines with context.\n"
        "     Pass path='src/agent/' not path='.' when using content mode to avoid noise.\n"
        "\n"
        "IMPORTANT: glob_pattern filters WHICH FILES to search (by name), NOT the regex.\n"
        "  glob_pattern='*.py' searches only .py files. The regex still matches inside those files.\n"
        "\n"
        "TROUBLESHOOTING — When grep returns no results or too many:\n"
        "- No matches: try case_sensitive=False, broader regex (e.g. 'error' not 'ErrorHandler'),\n"
        "  remove glob_pattern to search all files, or search a parent directory.\n"
        "- Too many matches: add glob_pattern='*.py' to filter, narrow path='src/agent/',\n"
        "  use a more specific regex, or reduce head_limit.\n"
        "- Content mode gives context lines around each match, but you STILL need view_file\n"
        "  to see the full file. The context is a hint, not a replacement for reading.\n"
        "- If offset exceeds total_matches, reduce offset or use head_limit=0 for all results.\n"
        "- The search skips .git/__pycache__/node_modules/.venv by default — these are\n"
        "  excluded to keep results relevant.\n"
        "\n"
        "Typical workflow:\n"
        "  1. grep(pattern='def login', output_mode='files_with_matches') → find files\n"
        "  2. view_file(file_path='auth.py') → read full context\n"
        "  3. str_replace(old_str='...', new_str='...') → make precise edit\n"
        "\n"
        "DO NOT edit a file based on grep output alone. You must view_file first.\n"
        "\n"
        "Examples:\n"
        "  pattern='def process_order' → returns file paths (default mode)\n"
        "  pattern='TODO|FIXME', glob_pattern='*.py' → finds TODO/FIXME in Python files\n"
        "  pattern='error', case_sensitive=False → finds error/ERROR/Error in all files\n"
        "  pattern='class\\s+\\w+.*:\\n\\s+def __init__', multiline=True\n"
        "    → finds class definitions with __init__ across multiple lines\n"
        "  pattern='import os', path='src/', output_mode='content', context_lines=1\n"
        "    → shows import statements in src/ with 1 line of context"
    ),
}
