"""
LLM-facing descriptions for the filesystem read tools.
"""

TOOL_DESCRIPTION = {
    "glob": (
        "Find files by glob pattern (e.g. '**/*.py'). Returns absolute paths.\n"
        "Params:\n"
        "- pattern: glob pattern. ** = recursive (crosses /), * = one level (no /, matches dots)\n"
        "- dir_path: directory to search (default '.')\n"
        "- allow_external_reads: read outside workspace (default False)\n"
        "EXCLUDED by default (not returned, not searched): dependency dirs "
        "(venv, .venv, node_modules, .npm, .yarn), version control (.git, .svn), "
        "IDE settings (.vscode, .idea, .cursor, .intellij), tool caches "
        "(__pycache__, .qoder, .cache, .gradle, .m2, .cargo), build outputs "
        "(dist, build, out, target, coverage), logs/temp (log, logs, .log, tmp), "
        "and noise files (.DS_Store). To scan inside an excluded dir, set "
        "dir_path to it directly.\n"
        "Limits: max 200 results, 5000 scanned. Check 'truncated' in response.\n"
        "No brace expansion {a,b} or extglob !(). Use multiple calls or regex via grep."
    ),
    "view_file": (
        "Read a file with line numbers. ALWAYS read before editing.\n"
        "Params:\n"
        "- file_path: path to the file\n"
        "- offset: start line, 1-based — first line is 1, NOT 0 (default 1)\n"
        "- limit: max lines to return, range 1-1000 (default 100)\n"
        "- encoding: file encoding (default 'utf-8', try 'gbk'/'latin-1')\n"
        "- allow_external_reads: read outside workspace (default False)\n"
        "EFFICIENCY RULES (save turns):\n"
        "- For files under ~1000 lines, set limit=1000 to read the WHOLE file in ONE call — do NOT paginate.\n"
        "- Need several files? Issue MULTIPLE view_file calls in the SAME turn — they execute in parallel.\n"
        "- Never re-read a file you already saw this task, unless you edited it. Its content is already in context.\n"
        "Limits: max 1MB read. If 'truncated' is true, use offset=end_line+1 to continue.\n"
        "Check 'remaining' field — if >0, you have NOT seen the whole file."
    ),
    "grep": (
        "Search file contents with regex. NAVIGATION tool — FIND where code lives, "
        "then use view_file to read. Do NOT edit based on grep output alone.\n"
        "Params:\n"
        "- pattern: regex pattern\n"
        "- path: file or dir to search (default '.')\n"
        "- glob_pattern: filter WHICH FILES by name, e.g. '*.py' (not the regex)\n"
        "- output_mode: files_with_matches|content|count (default files_with_matches)\n"
        "- context_lines: N lines before AND after each match, symmetric (default 2, range 0-10)\n"
        "- head_limit: max results (default 200, range 0-1000, 0=unlimited)\n"
        "- offset: skip first N match results, NOT line numbers (default 0)\n"
        "- case_sensitive: match case (default True)\n"
        "- multiline: . matches newlines, patterns can span lines; slower on large files (default False)\n"
        "- encoding: file encoding (default 'utf-8', try 'gbk'/'latin-1')\n"
        "- allow_external_reads: search outside workspace (default False)\n"
        "Strategy: start with files_with_matches to locate files, then content on a "
        "specific path to see matched lines. Limits: files >1MB skipped, max 5000 "
        "scanned. Response has 'files_truncated', 'skipped_large_files', 'timed_out_files'. "
        "If 'truncated' is true, increase offset for more."
    ),
}
